### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by avspera** [paramako/pornnub-api-client#3]
i'm trying to install you package in a Yii2 project. The composer refuses to install because:

`Could not find a version of package paramako/pornhub-api-client matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability`

can you please help me??

**Comment by paramako** [comment]
Hey!
I released v1.0 to match your minimum stability
Please try to drop composer cache and then reinstall the package
```
composer clear-cache
composer require paramako/pornhub-api-client
```
