### ISSUE TITLE
Pagination based on Category & Search

### ISSUE THREAD

**Issue by guevarawebgraphics** [paramako/pornnub-api-client#4]
Hello, would it be possible to request a feature of this wrapper. To get the list of pagination based from the category & search keywords?

As of now, I have this code

```
// searchVideo(category,page,keyword)
$videos =  $this->searchVideo('asian',1,'test');
```

```
 public function searchVideo( $category, $page, $search) {

        $client = \Paramako\Pornhub\Factory::create();
        $client->disableHttpErrorExceptions();
        $response = $client->videos()->get($category, $page, $search);

        return $response;
    }


```

**Comment by paramako** [comment]
Hey! Thank you for your interest in this package
I try to keep api client as small as possible, to give users an opportunity to do their own customisations over it, like yours mentioned above :)

also there is no need to create a new client every time you want to search for a video.
You can simply create it once instead and pass it everywhere you want
